// <auto-generated />
using System;
using GuessMyNation.Infra.Data.Sql.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuessMyNation.Infra.Data.Sql.Migrations
{
    [DbContext(typeof(GuessMyNationDbContext))]
    [Migration("20210713191512_refactor naming")]
    partial class refactornaming
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuessMyNation.Core.Domain.Game.GameDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("GameHeaderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GameHeaderId")
                        .IsUnique();

                    b.ToTable("GameDetail");
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Game.GameHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Nation.Nation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Nation.NationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnswerCode")
                        .HasColumnType("int");

                    b.Property<long>("NationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Point")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("NationItems");
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Nation.NationItemAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AnswerCode")
                        .HasColumnType("bigint");

                    b.Property<long?>("GameDetailId")
                        .HasColumnType("bigint");

                    b.Property<long>("NationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Point")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameDetailId");

                    b.ToTable("NationItemAnswer");
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Player.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Game.GameDetail", b =>
                {
                    b.HasOne("GuessMyNation.Core.Domain.Game.GameHeader", null)
                        .WithOne("Details")
                        .HasForeignKey("GuessMyNation.Core.Domain.Game.GameDetail", "GameHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Nation.NationItem", b =>
                {
                    b.HasOne("GuessMyNation.Core.Domain.Nation.Nation", "nation")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nation");
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Nation.NationItemAnswer", b =>
                {
                    b.HasOne("GuessMyNation.Core.Domain.Game.GameDetail", null)
                        .WithMany("NationItemAnswers")
                        .HasForeignKey("GameDetailId");
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Game.GameDetail", b =>
                {
                    b.Navigation("NationItemAnswers");
                });

            modelBuilder.Entity("GuessMyNation.Core.Domain.Game.GameHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
